# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Contributor: Trong Nhan Mai

version: '2.0'

services:

  mongo:
    image: mongo
    user: mongodb
    expose:
      - 27017

  web:
    image:
      <image_name>:<version>
    restart: on-failure
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      KEYSTONEJS_HOST: 0.0.0.0
    command: sh -c "sleep 5 && node ./node_modules/express-instrument-app/bin/run --projectDir /home/keystone/app --logFile log.file --enable-coverage test/e2e/server.js"
    ports:
      - "3000:3000"