version: '3.1'

services:

  mongo:
    image: mongo
    user: mongodb
    restart: always
    expose:
      - 27017

  web:
    build: .
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017
    command: sh -c "sleep 5 && node test/e2e/server.js --env default --notest"
    ports:
      - "3000:3000"
