# Copyright (c) 2020, 2020, Oracle and/or its affiliates.
# Contributor: Trong Nhan Mai
version: '3.1'

services:

  mongo:
    image: mongo
    user: mongodb
    restart: always
    expose:
      - 27017

  web:
    build: .
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      KEYSTONEJS_HOST: 0.0.0.0
    command: sh -c "sleep 5 && node test/e2e/server.js --env default --notest"
    ports:
      - "3000:3000"
