# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Contributor: Trong Nhan Mai

version: '2.0'

services:

  mongo:
    image: mongo:3
    restart: always
    expose:
      - "27017"

  web:
    image:
      <image_name>:<version>
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    command: 
      sh -c "sleep 5 && tini -- node ./express-instrument-app/bin/run --projectDir . --logFile log.file --enable-coverage app.js"
      #sh -c "tini -- npm start